Repository tibo-mllr/activeviam-projet, pull requests merged in 2025-01, with the labels that each got.

#57 feat: updating doc
  .github/pull_request_template.md
  README.md
Labels: documentation

#69 Fix issue #58: Scaling
  app/timeline/page.tsx
  components/timeline/CoreTimeline.tsx
Labels: bug

#79 Fixing issue #61 : add possibility to upload file
  app/submit-query/page.tsx
  components/FileUploader.tsx
  components/index.ts
Labels: enhancement

#98 Fixing issue #90 : being more clear about file inputs
  app/submit-query/page.tsx
  components/FileUploader.tsx
Labels: enhancement

#99 Fixing issue #89 : exporting Query plans as JSON files
  app/submit-query/page.tsx
  components/FileExporter.tsx
  components/index.ts
Labels: enhancement
